var classes = [
    {
        "name": "backend\\assets\\AppAsset",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "yii\\web\\AssetBundle"
        ],
        "parents": [
            "yii\\web\\AssetBundle"
        ],
        "lcom": 0,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 3,
        "loc": 12,
        "lloc": 9,
        "mi": 106.57,
        "mIwoC": 71.59,
        "commentWeight": 34.97,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "backend\\assets\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "backend\\controllers\\SiteController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "behaviors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionSignup",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionIndex",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionLogout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 12,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "yii\\web\\Controller",
            "yii\\filters\\AccessControl",
            "yii\\filters\\VerbFilter",
            "frontend\\models\\SignupForm",
            "common\\models\\LoginForm"
        ],
        "parents": [
            "yii\\web\\Controller"
        ],
        "lcom": 3,
        "length": 64,
        "vocabulary": 23,
        "volume": 289.51,
        "difficulty": 4.74,
        "effort": 1371.35,
        "level": 0.21,
        "bugs": 0.1,
        "time": 76,
        "intelligentContent": 61.12,
        "number_operators": 19,
        "number_operands": 45,
        "number_operators_unique": 4,
        "number_operands_unique": 19,
        "cloc": 29,
        "loc": 75,
        "lloc": 46,
        "mi": 86.61,
        "mIwoC": 45.55,
        "commentWeight": 41.05,
        "kanDefect": 0.5,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.75,
        "relativeSystemComplexity": 121.75,
        "totalStructuralComplexity": 726,
        "totalDataComplexity": 4.5,
        "totalSystemComplexity": 730.5,
        "package": "backend\\controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "common\\fixtures\\UserFixture",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "yii\\test\\ActiveFixture"
        ],
        "parents": [
            "yii\\test\\ActiveFixture"
        ],
        "lcom": 0,
        "length": 1,
        "vocabulary": 1,
        "volume": 0,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 0,
        "number_operators": 0,
        "number_operands": 1,
        "number_operators_unique": 0,
        "number_operands_unique": 1,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 171,
        "mIwoC": 171,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "common\\fixtures\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "common\\models\\Action",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDiscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWorkfun",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Discipline",
            "common\\models\\Workfunction",
            "common\\models\\Discipline",
            "common\\models\\Workfunction"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 4,
        "length": 42,
        "vocabulary": 19,
        "volume": 178.41,
        "difficulty": 1.03,
        "effort": 183.37,
        "level": 0.97,
        "bugs": 0.06,
        "time": 10,
        "intelligentContent": 173.59,
        "number_operators": 5,
        "number_operands": 37,
        "number_operators_unique": 1,
        "number_operands_unique": 18,
        "cloc": 26,
        "loc": 50,
        "lloc": 24,
        "mi": 98.94,
        "mIwoC": 53.99,
        "commentWeight": 44.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 6.25,
        "totalSystemComplexity": 51.25,
        "package": "common\\models\\",
        "pageRank": 0.05,
        "afferentCoupling": 6,
        "efferentCoupling": 3,
        "instability": 0.33,
        "violations": {}
    },
    {
        "name": "common\\models\\ActionSearch",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "scenarios",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "common\\models\\Action",
            "yii\\base\\Model",
            "common\\models\\Action",
            "yii\\data\\ActiveDataProvider"
        ],
        "parents": [
            "common\\models\\Action"
        ],
        "lcom": 3,
        "length": 34,
        "vocabulary": 14,
        "volume": 129.45,
        "difficulty": 3.68,
        "effort": 476.61,
        "level": 0.27,
        "bugs": 0.04,
        "time": 26,
        "intelligentContent": 35.16,
        "number_operators": 7,
        "number_operands": 27,
        "number_operators_unique": 3,
        "number_operands_unique": 11,
        "cloc": 21,
        "loc": 45,
        "lloc": 24,
        "mi": 98.41,
        "mIwoC": 54.83,
        "commentWeight": 43.58,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.72,
        "relativeSystemComplexity": 25.72,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 2.17,
        "totalSystemComplexity": 77.17,
        "package": "common\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "common\\models\\Can",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDiscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Discipline",
            "common\\models\\Discipline"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 4,
        "length": 28,
        "vocabulary": 16,
        "volume": 112,
        "difficulty": 0.8,
        "effort": 89.6,
        "level": 1.25,
        "bugs": 0.04,
        "time": 5,
        "intelligentContent": 140,
        "number_operators": 4,
        "number_operands": 24,
        "number_operators_unique": 1,
        "number_operands_unique": 15,
        "cloc": 21,
        "loc": 41,
        "lloc": 20,
        "mi": 101.89,
        "mIwoC": 57.14,
        "commentWeight": 44.76,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5.33,
        "totalSystemComplexity": 21.33,
        "package": "common\\models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "common\\models\\Discipline",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getActions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCans",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPlan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getKnows",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getKnowledges",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOwns",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSkills",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPlanList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 11,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Plan",
            "common\\models\\Action",
            "common\\models\\Can",
            "common\\models\\Plan",
            "common\\models\\Know",
            "common\\models\\Knowledge",
            "common\\models\\Own",
            "common\\models\\Skill",
            "common\\models\\Plan",
            "yii\\helpers\\ArrayHelper"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 6,
        "length": 56,
        "vocabulary": 18,
        "volume": 233.52,
        "difficulty": 1.32,
        "effort": 309.07,
        "level": 0.76,
        "bugs": 0.08,
        "time": 17,
        "intelligentContent": 176.43,
        "number_operators": 11,
        "number_operands": 45,
        "number_operators_unique": 1,
        "number_operands_unique": 17,
        "cloc": 45,
        "loc": 93,
        "lloc": 48,
        "mi": 90.65,
        "mIwoC": 46.61,
        "commentWeight": 44.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.92,
        "relativeSystemComplexity": 121.92,
        "totalStructuralComplexity": 1331,
        "totalDataComplexity": 10.08,
        "totalSystemComplexity": 1341.08,
        "package": "common\\models\\",
        "pageRank": 0.16,
        "afferentCoupling": 11,
        "efferentCoupling": 9,
        "instability": 0.45,
        "violations": {}
    },
    {
        "name": "common\\models\\DisciplineSearch",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "scenarios",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "common\\models\\Discipline",
            "yii\\base\\Model",
            "common\\models\\Discipline",
            "yii\\data\\ActiveDataProvider"
        ],
        "parents": [
            "common\\models\\Discipline"
        ],
        "lcom": 3,
        "length": 31,
        "vocabulary": 13,
        "volume": 114.71,
        "difficulty": 3.6,
        "effort": 412.97,
        "level": 0.28,
        "bugs": 0.04,
        "time": 23,
        "intelligentContent": 31.86,
        "number_operators": 7,
        "number_operands": 24,
        "number_operators_unique": 3,
        "number_operands_unique": 10,
        "cloc": 21,
        "loc": 45,
        "lloc": 24,
        "mi": 98.78,
        "mIwoC": 55.2,
        "commentWeight": 43.58,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.72,
        "relativeSystemComplexity": 25.72,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 2.17,
        "totalSystemComplexity": 77.17,
        "package": "common\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 3,
        "efferentCoupling": 3,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "common\\models\\General",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProfession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWorkfunctions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Profession",
            "common\\models\\Profession",
            "common\\models\\Workfunction"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 5,
        "length": 45,
        "vocabulary": 24,
        "volume": 206.32,
        "difficulty": 0.87,
        "effort": 179.41,
        "level": 1.15,
        "bugs": 0.07,
        "time": 10,
        "intelligentContent": 237.27,
        "number_operators": 5,
        "number_operands": 40,
        "number_operators_unique": 1,
        "number_operands_unique": 23,
        "cloc": 27,
        "loc": 51,
        "lloc": 24,
        "mi": 98.71,
        "mIwoC": 53.55,
        "commentWeight": 45.16,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 17,
        "totalStructuralComplexity": 80,
        "totalDataComplexity": 5,
        "totalSystemComplexity": 85,
        "package": "common\\models\\",
        "pageRank": 0.07,
        "afferentCoupling": 2,
        "efferentCoupling": 3,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "common\\models\\Know",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDiscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Discipline",
            "common\\models\\Discipline"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 4,
        "length": 28,
        "vocabulary": 16,
        "volume": 112,
        "difficulty": 0.8,
        "effort": 89.6,
        "level": 1.25,
        "bugs": 0.04,
        "time": 5,
        "intelligentContent": 140,
        "number_operators": 4,
        "number_operands": 24,
        "number_operators_unique": 1,
        "number_operands_unique": 15,
        "cloc": 21,
        "loc": 41,
        "lloc": 20,
        "mi": 101.89,
        "mIwoC": 57.14,
        "commentWeight": 44.76,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5.33,
        "totalSystemComplexity": 21.33,
        "package": "common\\models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "common\\models\\Knowledge",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDiscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWorkfunction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Discipline",
            "common\\models\\Workfunction",
            "common\\models\\Discipline",
            "common\\models\\Workfunction"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 4,
        "length": 42,
        "vocabulary": 18,
        "volume": 175.14,
        "difficulty": 1.09,
        "effort": 190.59,
        "level": 0.92,
        "bugs": 0.06,
        "time": 11,
        "intelligentContent": 160.94,
        "number_operators": 5,
        "number_operands": 37,
        "number_operators_unique": 1,
        "number_operands_unique": 17,
        "cloc": 26,
        "loc": 50,
        "lloc": 24,
        "mi": 98.99,
        "mIwoC": 54.05,
        "commentWeight": 44.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 6.25,
        "totalSystemComplexity": 51.25,
        "package": "common\\models\\",
        "pageRank": 0.04,
        "afferentCoupling": 5,
        "efferentCoupling": 3,
        "instability": 0.38,
        "violations": {}
    },
    {
        "name": "common\\models\\LoginForm",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validatePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "login",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUser",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 1,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "yii\\base\\Model",
            "common\\models\\User"
        ],
        "parents": [
            "yii\\base\\Model"
        ],
        "lcom": 2,
        "length": 43,
        "vocabulary": 21,
        "volume": 188.87,
        "difficulty": 5.8,
        "effort": 1095.44,
        "level": 0.17,
        "bugs": 0.06,
        "time": 61,
        "intelligentContent": 32.56,
        "number_operators": 14,
        "number_operands": 29,
        "number_operators_unique": 6,
        "number_operands_unique": 15,
        "cloc": 26,
        "loc": 65,
        "lloc": 39,
        "mi": 89.93,
        "mIwoC": 48.41,
        "commentWeight": 41.52,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.56,
        "relativeSystemComplexity": 49.56,
        "totalStructuralComplexity": 196,
        "totalDataComplexity": 2.25,
        "totalSystemComplexity": 198.25,
        "package": "common\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "common\\models\\Own",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDiscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 4,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Discipline",
            "common\\models\\Discipline"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 4,
        "length": 28,
        "vocabulary": 16,
        "volume": 112,
        "difficulty": 0.8,
        "effort": 89.6,
        "level": 1.25,
        "bugs": 0.04,
        "time": 5,
        "intelligentContent": 140,
        "number_operators": 4,
        "number_operands": 24,
        "number_operators_unique": 1,
        "number_operands_unique": 15,
        "cloc": 21,
        "loc": 41,
        "lloc": 20,
        "mi": 101.89,
        "mIwoC": 57.14,
        "commentWeight": 44.76,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.33,
        "relativeSystemComplexity": 5.33,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 5.33,
        "totalSystemComplexity": 21.33,
        "package": "common\\models\\",
        "pageRank": 0.02,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "common\\models\\Plan",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDisciplines",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProfession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProfessions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getProfList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Profession",
            "common\\models\\Discipline",
            "common\\models\\Profession",
            "common\\models\\Profession",
            "common\\models\\Profession",
            "yii\\helpers\\ArrayHelper"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 6,
        "length": 52,
        "vocabulary": 25,
        "volume": 241.48,
        "difficulty": 0.94,
        "effort": 226.39,
        "level": 1.07,
        "bugs": 0.08,
        "time": 13,
        "intelligentContent": 257.58,
        "number_operators": 7,
        "number_operands": 45,
        "number_operators_unique": 1,
        "number_operands_unique": 24,
        "cloc": 31,
        "loc": 63,
        "lloc": 32,
        "mi": 94.6,
        "mIwoC": 50.35,
        "commentWeight": 44.26,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 37,
        "totalStructuralComplexity": 252,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 259,
        "package": "common\\models\\",
        "pageRank": 0.17,
        "afferentCoupling": 4,
        "efferentCoupling": 4,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "common\\models\\PlanSearch",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "scenarios",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "common\\models\\Plan",
            "yii\\base\\Model",
            "common\\models\\Plan",
            "yii\\data\\ActiveDataProvider"
        ],
        "parents": [
            "common\\models\\Plan"
        ],
        "lcom": 3,
        "length": 38,
        "vocabulary": 15,
        "volume": 148.46,
        "difficulty": 3.88,
        "effort": 575.29,
        "level": 0.26,
        "bugs": 0.05,
        "time": 32,
        "intelligentContent": 38.31,
        "number_operators": 7,
        "number_operands": 31,
        "number_operators_unique": 3,
        "number_operands_unique": 12,
        "cloc": 21,
        "loc": 45,
        "lloc": 24,
        "mi": 97.99,
        "mIwoC": 54.42,
        "commentWeight": 43.58,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.72,
        "relativeSystemComplexity": 25.72,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 2.17,
        "totalSystemComplexity": 77.17,
        "package": "common\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "common\\models\\Profession",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getGenerals",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPlans",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPlan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPlanList",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Plan",
            "common\\models\\General",
            "common\\models\\Plan",
            "common\\models\\Plan",
            "common\\models\\Plan",
            "yii\\helpers\\ArrayHelper"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 6,
        "length": 59,
        "vocabulary": 27,
        "volume": 280.54,
        "difficulty": 1,
        "effort": 280.54,
        "level": 1,
        "bugs": 0.09,
        "time": 16,
        "intelligentContent": 280.54,
        "number_operators": 7,
        "number_operands": 52,
        "number_operators_unique": 1,
        "number_operands_unique": 26,
        "cloc": 32,
        "loc": 64,
        "lloc": 32,
        "mi": 94.35,
        "mIwoC": 49.89,
        "commentWeight": 44.46,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 37,
        "totalStructuralComplexity": 252,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 259,
        "package": "common\\models\\",
        "pageRank": 0.16,
        "afferentCoupling": 4,
        "efferentCoupling": 4,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "common\\models\\ProfessionSearch",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "scenarios",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "search",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "common\\models\\Profession",
            "yii\\base\\Model",
            "common\\models\\Profession",
            "yii\\data\\ActiveDataProvider"
        ],
        "parents": [
            "common\\models\\Profession"
        ],
        "lcom": 3,
        "length": 42,
        "vocabulary": 16,
        "volume": 168,
        "difficulty": 4.04,
        "effort": 678.46,
        "level": 0.25,
        "bugs": 0.06,
        "time": 38,
        "intelligentContent": 41.6,
        "number_operators": 7,
        "number_operands": 35,
        "number_operators_unique": 3,
        "number_operands_unique": 13,
        "cloc": 21,
        "loc": 45,
        "lloc": 24,
        "mi": 97.62,
        "mIwoC": 54.04,
        "commentWeight": 43.58,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.72,
        "relativeSystemComplexity": 25.72,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 2.17,
        "totalSystemComplexity": 77.17,
        "package": "common\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 3,
        "instability": 0.75,
        "violations": {}
    },
    {
        "name": "common\\models\\Skill",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDiscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getWorkfunction",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\Discipline",
            "common\\models\\Workfunction",
            "common\\models\\Discipline",
            "common\\models\\Workfunction"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 4,
        "length": 42,
        "vocabulary": 18,
        "volume": 175.14,
        "difficulty": 1.09,
        "effort": 190.59,
        "level": 0.92,
        "bugs": 0.06,
        "time": 11,
        "intelligentContent": 160.94,
        "number_operators": 5,
        "number_operands": 37,
        "number_operators_unique": 1,
        "number_operands_unique": 17,
        "cloc": 26,
        "loc": 50,
        "lloc": 24,
        "mi": 98.99,
        "mIwoC": 54.05,
        "commentWeight": 44.94,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 9,
        "relativeDataComplexity": 1.25,
        "relativeSystemComplexity": 10.25,
        "totalStructuralComplexity": 45,
        "totalDataComplexity": 6.25,
        "totalSystemComplexity": 51.25,
        "package": "common\\models\\",
        "pageRank": 0.04,
        "afferentCoupling": 5,
        "efferentCoupling": 3,
        "instability": 0.38,
        "violations": {}
    },
    {
        "name": "common\\models\\User",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "behaviors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findIdentity",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findIdentityByAccessToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findByUsername",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "findByPasswordResetToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isPasswordResetTokenValid",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAuthKey",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateAuthKey",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validatePassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateAuthKey",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generatePasswordResetToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "removePasswordResetToken",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 16,
        "nbMethods": 15,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 15,
        "nbMethodsGetter": 1,
        "nbMethodsSetters": 0,
        "wmc": 18,
        "ccn": 3,
        "ccnMethodMax": 2,
        "externals": [
            "yii\\db\\ActiveRecord",
            "yii\\web\\IdentityInterface",
            "yii\\behaviors\\TimestampBehavior",
            "static",
            "yii\\base\\NotSupportedException",
            "static",
            "static",
            "static"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 10,
        "length": 79,
        "vocabulary": 30,
        "volume": 387.64,
        "difficulty": 7.91,
        "effort": 3067.45,
        "level": 0.13,
        "bugs": 0.13,
        "time": 170,
        "intelligentContent": 48.99,
        "number_operators": 27,
        "number_operands": 52,
        "number_operators_unique": 7,
        "number_operands_unique": 23,
        "cloc": 76,
        "loc": 154,
        "lloc": 78,
        "mi": 84.49,
        "mIwoC": 40.2,
        "commentWeight": 44.29,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.7,
        "relativeSystemComplexity": 50.7,
        "totalStructuralComplexity": 784,
        "totalDataComplexity": 27.13,
        "totalSystemComplexity": 811.13,
        "package": "common\\models\\",
        "pageRank": 0.02,
        "afferentCoupling": 4,
        "efferentCoupling": 5,
        "instability": 0.56,
        "violations": {}
    },
    {
        "name": "common\\models\\Workfunction",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "tableName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getActions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getKnowledges",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSkills",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getGeneral",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 7,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\db\\ActiveRecord",
            "common\\models\\General",
            "common\\models\\Action",
            "common\\models\\Knowledge",
            "common\\models\\Skill",
            "common\\models\\General"
        ],
        "parents": [
            "yii\\db\\ActiveRecord"
        ],
        "lcom": 5,
        "length": 56,
        "vocabulary": 26,
        "volume": 263.22,
        "difficulty": 0.98,
        "effort": 257.96,
        "level": 1.02,
        "bugs": 0.09,
        "time": 14,
        "intelligentContent": 268.6,
        "number_operators": 7,
        "number_operands": 49,
        "number_operators_unique": 1,
        "number_operands_unique": 25,
        "cloc": 35,
        "loc": 67,
        "lloc": 32,
        "mi": 95.08,
        "mIwoC": 50.09,
        "commentWeight": 45,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 37,
        "totalStructuralComplexity": 252,
        "totalDataComplexity": 7,
        "totalSystemComplexity": 259,
        "package": "common\\models\\",
        "pageRank": 0.09,
        "afferentCoupling": 4,
        "efferentCoupling": 5,
        "instability": 0.56,
        "violations": {}
    },
    {
        "name": "common\\widgets\\Alert",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "run",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "yii\\bootstrap\\Widget",
            "yii\\bootstrap\\Alert"
        ],
        "parents": [
            "yii\\bootstrap\\Widget"
        ],
        "lcom": 1,
        "length": 57,
        "vocabulary": 29,
        "volume": 276.9,
        "difficulty": 2.71,
        "effort": 750.84,
        "level": 0.37,
        "bugs": 0.09,
        "time": 42,
        "intelligentContent": 102.12,
        "number_operators": 10,
        "number_operands": 47,
        "number_operators_unique": 3,
        "number_operands_unique": 26,
        "cloc": 32,
        "loc": 53,
        "lloc": 21,
        "mi": 100.05,
        "mIwoC": 53.38,
        "commentWeight": 46.67,
        "kanDefect": 0.68,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 16,
        "totalStructuralComplexity": 16,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 16,
        "package": "common\\widgets\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 2,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "m130524_201442_init",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "up",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "down",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "yii\\db\\Migration"
        ],
        "parents": [
            "yii\\db\\Migration"
        ],
        "lcom": 2,
        "length": 34,
        "vocabulary": 19,
        "volume": 144.43,
        "difficulty": 2.81,
        "effort": 406.21,
        "level": 0.36,
        "bugs": 0.05,
        "time": 23,
        "intelligentContent": 51.35,
        "number_operators": 4,
        "number_operands": 30,
        "number_operators_unique": 3,
        "number_operands_unique": 16,
        "cloc": 1,
        "loc": 17,
        "lloc": 16,
        "mi": 76.69,
        "mIwoC": 58.34,
        "commentWeight": 18.35,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 81,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 81,
        "totalStructuralComplexity": 162,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 162,
        "package": "common\\widgets\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "frontend\\assets\\AppAsset",
        "interface": false,
        "abstract": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [
            "yii\\web\\AssetBundle"
        ],
        "parents": [
            "yii\\web\\AssetBundle"
        ],
        "lcom": 0,
        "length": 5,
        "vocabulary": 5,
        "volume": 11.61,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0,
        "time": 0,
        "intelligentContent": 23.22,
        "number_operators": 0,
        "number_operands": 5,
        "number_operators_unique": 0,
        "number_operands_unique": 5,
        "cloc": 3,
        "loc": 12,
        "lloc": 9,
        "mi": 106.57,
        "mIwoC": 71.59,
        "commentWeight": 34.97,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "frontend\\assets\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "frontend\\controllers\\HeadController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "behaviors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionDiscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionDisciplineone",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionActionlist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionActionown",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionPlan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionCreateplan",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionProfession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionCreateprofession",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 10,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 15,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "yii\\web\\Controller",
            "yii\\filters\\AccessControl",
            "yii\\filters\\VerbFilter",
            "common\\models\\DisciplineSearch",
            "common\\models\\Discipline",
            "common\\models\\Action",
            "common\\models\\Skill",
            "common\\models\\Knowledge",
            "common\\models\\ActionSearch",
            "common\\models\\Action",
            "common\\models\\PlanSearch",
            "common\\models\\Plan",
            "common\\models\\ProfessionSearch",
            "common\\models\\Profession"
        ],
        "parents": [
            "yii\\web\\Controller"
        ],
        "lcom": 3,
        "length": 140,
        "vocabulary": 39,
        "volume": 739.96,
        "difficulty": 6.23,
        "effort": 4608.87,
        "level": 0.16,
        "bugs": 0.25,
        "time": 256,
        "intelligentContent": 118.8,
        "number_operators": 31,
        "number_operands": 109,
        "number_operators_unique": 4,
        "number_operands_unique": 35,
        "cloc": 3,
        "loc": 71,
        "lloc": 68,
        "mi": 54.78,
        "mIwoC": 39.13,
        "commentWeight": 15.65,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.82,
        "relativeSystemComplexity": 196.82,
        "totalStructuralComplexity": 1960,
        "totalDataComplexity": 8.2,
        "totalSystemComplexity": 1968.2,
        "package": "frontend\\controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 13,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "frontend\\controllers\\SiteController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "behaviors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionLogin",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionLogout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionRequestPasswordReset",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionResetPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionRole",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionDiscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionCreatediscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionDisciplineone",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionActionlist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionActionown",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 12,
        "nbMethods": 12,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 12,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 30,
        "ccn": 19,
        "ccnMethodMax": 5,
        "externals": [
            "yii\\web\\Controller",
            "yii\\filters\\AccessControl",
            "yii\\filters\\VerbFilter",
            "common\\models\\LoginForm",
            "frontend\\models\\PasswordResetRequestForm",
            "frontend\\models\\ResetPasswordForm",
            "yii\\web\\BadRequestHttpException",
            "common\\models\\DisciplineSearch",
            "common\\models\\Discipline",
            "common\\models\\Discipline",
            "common\\models\\Action",
            "common\\models\\Skill",
            "common\\models\\Knowledge",
            "common\\models\\ActionSearch",
            "common\\models\\Action"
        ],
        "parents": [
            "yii\\web\\Controller"
        ],
        "lcom": 4,
        "length": 195,
        "vocabulary": 51,
        "volume": 1106.12,
        "difficulty": 7.66,
        "effort": 8476.27,
        "level": 0.13,
        "bugs": 0.37,
        "time": 471,
        "intelligentContent": 144.35,
        "number_operators": 54,
        "number_operands": 141,
        "number_operators_unique": 5,
        "number_operands_unique": 46,
        "cloc": 31,
        "loc": 142,
        "lloc": 111,
        "mi": 64.63,
        "mIwoC": 31.52,
        "commentWeight": 33.11,
        "kanDefect": 0.92,
        "relativeStructuralComplexity": 676,
        "relativeDataComplexity": 0.64,
        "relativeSystemComplexity": 676.64,
        "totalStructuralComplexity": 8112,
        "totalDataComplexity": 7.7,
        "totalSystemComplexity": 8119.7,
        "package": "frontend\\controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 13,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "frontend\\controllers\\TeacherController",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "behaviors",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actions",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionLogout",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionDiscipline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionDisciplineone",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionActionlist",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "actionActionown",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "yii\\web\\Controller",
            "yii\\filters\\AccessControl",
            "yii\\filters\\VerbFilter",
            "common\\models\\DisciplineSearch",
            "common\\models\\Discipline",
            "common\\models\\Action",
            "common\\models\\Skill",
            "common\\models\\Knowledge",
            "common\\models\\ActionSearch",
            "common\\models\\Action"
        ],
        "parents": [
            "yii\\web\\Controller"
        ],
        "lcom": 4,
        "length": 89,
        "vocabulary": 32,
        "volume": 445,
        "difficulty": 2.43,
        "effort": 1082.83,
        "level": 0.41,
        "bugs": 0.15,
        "time": 60,
        "intelligentContent": 182.88,
        "number_operators": 16,
        "number_operands": 73,
        "number_operators_unique": 2,
        "number_operands_unique": 30,
        "cloc": 8,
        "loc": 50,
        "lloc": 42,
        "mi": 74.82,
        "mIwoC": 45.78,
        "commentWeight": 29.04,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 144,
        "relativeDataComplexity": 0.57,
        "relativeSystemComplexity": 144.57,
        "totalStructuralComplexity": 1008,
        "totalDataComplexity": 4,
        "totalSystemComplexity": 1012,
        "package": "frontend\\controllers\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "frontend\\models\\ContactForm",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "attributeLabels",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "yii\\base\\Model"
        ],
        "parents": [
            "yii\\base\\Model"
        ],
        "lcom": 3,
        "length": 20,
        "vocabulary": 10,
        "volume": 66.44,
        "difficulty": 0.94,
        "effort": 62.75,
        "level": 1.06,
        "bugs": 0.02,
        "time": 3,
        "intelligentContent": 70.35,
        "number_operators": 3,
        "number_operands": 17,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 18,
        "loc": 43,
        "lloc": 25,
        "mi": 98.75,
        "mIwoC": 56.61,
        "commentWeight": 42.14,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.48,
        "relativeSystemComplexity": 36.48,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 1.43,
        "totalSystemComplexity": 109.43,
        "package": "frontend\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 0,
        "efferentCoupling": 1,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "frontend\\models\\PasswordResetRequestForm",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "sendEmail",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "yii\\base\\Model",
            "common\\models\\User",
            "common\\models\\User"
        ],
        "parents": [
            "yii\\base\\Model"
        ],
        "lcom": 2,
        "length": 42,
        "vocabulary": 23,
        "volume": 189.99,
        "difficulty": 3.37,
        "effort": 639.96,
        "level": 0.3,
        "bugs": 0.06,
        "time": 36,
        "intelligentContent": 56.4,
        "number_operators": 10,
        "number_operands": 32,
        "number_operators_unique": 4,
        "number_operands_unique": 19,
        "cloc": 12,
        "loc": 35,
        "lloc": 23,
        "mi": 93.19,
        "mIwoC": 53.8,
        "commentWeight": 39.39,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 64,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 64.44,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 0.89,
        "totalSystemComplexity": 128.89,
        "package": "frontend\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    },
    {
        "name": "frontend\\models\\ResetPasswordForm",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resetPassword",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "yii\\base\\Model",
            "yii\\base\\InvalidParamException",
            "common\\models\\User",
            "yii\\base\\InvalidParamException",
            "parent"
        ],
        "parents": [
            "yii\\base\\Model"
        ],
        "lcom": 2,
        "length": 29,
        "vocabulary": 15,
        "volume": 113.3,
        "difficulty": 4,
        "effort": 453.2,
        "level": 0.25,
        "bugs": 0.04,
        "time": 25,
        "intelligentContent": 28.32,
        "number_operators": 7,
        "number_operands": 22,
        "number_operators_unique": 4,
        "number_operands_unique": 11,
        "cloc": 21,
        "loc": 49,
        "lloc": 28,
        "mi": 95.96,
        "mIwoC": 53.51,
        "commentWeight": 42.45,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 25,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 25.44,
        "totalStructuralComplexity": 75,
        "totalDataComplexity": 1.33,
        "totalSystemComplexity": 76.33,
        "package": "frontend\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "frontend\\models\\SignupForm",
        "interface": false,
        "abstract": false,
        "methods": [
            {
                "name": "rules",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "signup",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 3,
        "ccnMethodMax": 3,
        "externals": [
            "yii\\base\\Model",
            "common\\models\\User"
        ],
        "parents": [
            "yii\\base\\Model"
        ],
        "lcom": 2,
        "length": 56,
        "vocabulary": 22,
        "volume": 249.73,
        "difficulty": 3.87,
        "effort": 966.05,
        "level": 0.26,
        "bugs": 0.08,
        "time": 54,
        "intelligentContent": 64.56,
        "number_operators": 7,
        "number_operands": 49,
        "number_operators_unique": 3,
        "number_operands_unique": 19,
        "cloc": 11,
        "loc": 34,
        "lloc": 23,
        "mi": 91.68,
        "mIwoC": 53.1,
        "commentWeight": 38.57,
        "kanDefect": 0.22,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 0.6,
        "relativeSystemComplexity": 16.6,
        "totalStructuralComplexity": 32,
        "totalDataComplexity": 1.2,
        "totalSystemComplexity": 33.2,
        "package": "frontend\\models\\",
        "pageRank": 0.01,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    }
]